send_job: # 定义job名称
  install:
    - echo "install sth here"
  before_script:
    - echo "before script"
  script:
    - echo "hello world"
    - pwd
    - ls -l
    - uname -a
    - gcc -v
  after_script:
    - echo "my env " $PASSWD
    - echo "ci env "  $name
    - echo "ci env "  $noname
  ## 环境变量，注意，这是脚本内的环境变量
  env:
    global:
      - PASSWD: pw123456
  only:
    - master