send_job:
  before_script:
    - apt-get update -qq && apt-get install -y -qq software-properties-common
    - curl -sL https://deb.nodesource.com/setup_10.x | bash -
    - echo "install nodejs"
    - apt-get update -qq && apt-get install -y -qq nodejs
    - node -v
    - npm -v
    - npm install nodemailer
  script:
    - echo "running mail.js"
    - node .gitemail.js "li@latelee.org, latelee@163.com" "CICD实践项目" https://gitlab.com/latelee/ci

  after_script:
    - echo "after script..."
  only:
    - master