stages:
    - build
    - deploy
build:
  stage: build
  image: docker:stable
  services:
    - docker:dind
  variables:
    foo: hello world
  script:
    - echo "env" $foo
    - echo "building docker"
    - docker build -t k8s_tar 1.8.15
    - docker images
  after_script:
    - echo "after script"

deploy:
  stage: deploy
  script:
    - echo "deploy stage"