stages: # 本次构建分2个阶段，GitLab会分2次构建
  - build
  - deploy
build: # build阶段
  stage: build
  image: docker:stable
  services:
    - docker:dind # dind表示docker in docker
  variables: # 设置环境变量，供脚本使用
    foo: hello world
  script:
    - echo "env" $foo
    - echo "building docker"
    - docker build -t k8s_tar 1.8.15
    - docker images
  after_script:
    - echo "after script"

deploy: # deploy阶段
  stage: deploy
  script:
    - echo "deploy stage"