my_job: # 定义job名称
stages:
  - build
stages:
  stage: build
  images: docker:stable
  services:
    - docker: dind
  variables:
    foo: helloworld
  before_script:
    - echo "before script"
  script:
    - echo "building docker"
    - docker build -t k8s_tar 1.8.15
    - docker images
  after_script:
    - echo "after script"
  only:
    - master