send_job: # 定义job名称
  before_script:
    - echo "before script"
  script:
    - echo "hello world"
    - pwd
    - ls -l
    - uname -a
    - gcc -v
  after_script:
    - echo "my env " $PASSWD
    - echo "ci env "  $name
    - echo "ci env "  $noname
  only:
    - master