stages:
  - build
build:
  stage: build
  images: docker:stable
  services:
    - docker: dind
  variables:
    foo:hell world
  script:
    - echo "env" $foo
    - echo "building docker"
    - docker build -t k8s_tar 1.8.15
    - docker images
  after_script:
    - echo "after script"
  only:
    - master