version: 2.1
jobs:
  build:
    docker: 
      - image: circleci/node:11.6.0
    steps:
      - checkout # check out the code in the project directory
      - run: echo "hello world" # run the `echo` command
      - run: echo "my env " $PASSWD
      - run: echo "circleci nonexist" $nopath
      - run: pwd
      - run: ls -l
      - run: uname -a
      - run: gcc -v
